# Build the package, make sure it compiles OK

name: Build Package

on:
  - push
  - pull_request

jobs:

  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python Dependencies
        run: |
          pip install --upgrade wheel setuptools twine build
          pip install flake8 pep8-naming
      - name: Build Package
        run: |
          pip install .
      - name: Generate plugin
        run: |
          create-inventree-plugin --default --output output
          test -d output || echo "Output directory not found"
          test -d output/MyCustomPlugin || echo "Plugin directory not found"
          test -d output/MyCustomPlugin/src || echo "Source directory not found"
          test -f output/MyCustomPlugin/src/__init__.py || echo "__init__.py not found"
          test -f output/MyCustomPlugin/src/plugin.py || echo "plugin.py not found"
          test -f output/MyCustomPlugin/README.md || echo "README.md not found"
      - name: Build and Install Plugin
        run: |
          cd output/MyCustomPlugin
          flake8 .
          pip install .
