# Build the package, make sure it compiles OK

name: Build Package

on:
  - push
  - pull_request

jobs:

  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python Dependencies
        run: |
          pip install --upgrade wheel setuptools twine build
      - name: Build Package
        run: |
          pip install .
      - name: Generate plugin
        run: |
          create-inventree-plugin --default --output my_plugin
          test -d my_plugin
          test -d my_plugin/MyCustomPlugin
          test -d my_plugin/MyCustomPlugin/src
          test -f my_plugin/MyCustomPlugin/src/__init__.py
          test -f my_plugin/MyCustomPlugin/src/plugin.py
          test -f my_plugin/MyCustomPlugin/README.md
